services:
  frontend:
    image: ghcr.io/im-malik/delogger-frontend:v1.0
    ports:
      - 80
    restart: on-failure:3
    depends_on: 
      - backend
    volumes:
      - /var/log/delogger/nginx:/var/log/nginx

  backend:
    image: ghcr.io/im-malik/delogger-backend:v1.0
    ports:
      - 8001
    restart: on-failure:3

  db:
    image: postgres
    ports: 
      - 5432:5432
    restart: on-failure:3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - /var/log/delogger/db:/var/lib/postgresql/data